package gui;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JToolBar;
import javax.swing.JButton;

public class musa_configuration_panel extends JFrame {

	private JPanel contentPane;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					musa_configuration_panel frame = new musa_configuration_panel();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public musa_configuration_panel() {
		initComponents();
	}
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_inject_selection = new javax.swing.JButton();
        btn_inject_goal_pack = new javax.swing.JButton();
        btn_submit_new_goal = new javax.swing.JButton();
        btn_merge_goals = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btn_inject_selection.setText("Inject selection");
        btn_inject_selection.setFocusable(false);
        btn_inject_selection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_inject_selection.setName(""); // NOI18N
        btn_inject_selection.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_inject_selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inject_selectionActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_inject_selection);

        btn_inject_goal_pack.setText("Inject goal pack");
        btn_inject_goal_pack.setFocusable(false);
        btn_inject_goal_pack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_inject_goal_pack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_inject_goal_pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inject_goal_packActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_inject_goal_pack);

        btn_submit_new_goal.setText("Submit new goal");
        btn_submit_new_goal.setFocusable(false);
        btn_submit_new_goal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_submit_new_goal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_submit_new_goal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submit_new_goalActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_submit_new_goal);

        btn_merge_goals.setText("Merge goals");
        btn_merge_goals.setFocusable(false);
        btn_merge_goals.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_merge_goals.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_merge_goals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_merge_goalsActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_merge_goals);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Pack", "Description"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btn_inject_selectionActionPerformed(java.awt.event.ActionEvent evt) 
    {                                                     
        // TODO add your handling code here:
    }                                                    

    private void btn_inject_goal_packActionPerformed(java.awt.event.ActionEvent evt) 
    {                                                     
        // TODO add your handling code here:
    }                                                    

    private void btn_submit_new_goalActionPerformed(java.awt.event.ActionEvent evt) 
    {                                                    
        // TODO add your handling code here:
    }                                                   

    private void btn_merge_goalsActionPerformed(java.awt.event.ActionEvent evt) 
    {                                                
        // TODO add your handling code here:
    }                                               

    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_inject_goal_pack;
    private javax.swing.JButton btn_inject_selection;
    private javax.swing.JButton btn_merge_goals;
    private javax.swing.JButton btn_submit_new_goal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration                   
}


